services:
  backend:
    build:
      context: ./backend
    container_name: tailor-cv-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ~/.aws:/root/.aws:ro
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: tailor-cv-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
